
package Vista;

import Control.CtrLogin;
import Control.CtrlCaja;
import Modelo.TurnoCaja;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.sql.Time;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {
    CtrlCaja objCtrlCa=new CtrlCaja();
    CtrLogin objCtrlL=new CtrLogin();
    public static int CODIGOCAJA;
    public static String DESCRIPCIONCAJA;
    public static int MPIDUSUARIO;
    public static String MPNOMBREUSUARIO; 
    
    public static int IDTURNOCAJA;
    
    UsuarioGui usuario;

    
    public MenuPrincipal() {
        initComponents();
        CODIGOCAJA=0;
        DESCRIPCIONCAJA="";
        MPIDUSUARIO=0;
        MPNOMBREUSUARIO="";
        IDTURNOCAJA=0;
        this.setTitle( "Papiro de Gato - versión 1.0.1" );
        this.getContentPane().setBackground(Color.WHITE);        
        setLocationRelativeTo(null);
        pedirCodigoCaja();
        
        
        if(Principal.NOMROL.equalsIgnoreCase("Empleado")){
            
            btnUsuario.setEnabled(false);           
//            jMenuResoFactura.setEnabled(false);no va
//            jMenuReportes.setEnabled(false);no va
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JToggleButton();
        contenedor = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(77, 182, 172));

        buttonGroup1.add(btnUsuario);
        btnUsuario.setText("Usuario");
        btnUsuario.setToolTipText("Accede a Usuarios");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1341, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        jMenuBar.setBackground(new java.awt.Color(178, 223, 219));
        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenedor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void pedirCodigoCaja(){
        boolean bandera=true;
        int codigoCaja=0;
        do{
            try{
               codigoCaja=Integer.valueOf(JOptionPane.showInputDialog("<html><h2>Digite por favor el codigo de la caja:</h2></html>"));
              // JOptionPane.showMessageDialog(null,"codigoCaja="+codigoCaja+" \nfechaActual="+fechaNow()+" Hora inicial="+ horaNow());
            }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null,"<html><h3 style='color:red;'>Codigo de caja Invalido!</h3></html>"); 
               bandera=false;
            }
            
            if(objCtrlCa.buscarCajaXcodigo(codigoCaja)==1){//BUSCA QUE EL CODIGO DIGITADO EXISTA! osea que aqui deja SEGUIR!
                bandera=true;
                JOptionPane.showMessageDialog(null,"<html><h3 style='color:green;'>Codigo de caja Aceptado</h3></html>");
                CODIGOCAJA=codigoCaja;
                DESCRIPCIONCAJA=objCtrlCa.buscarDescCaja(codigoCaja);
                MPIDUSUARIO=Principal.IDUSUARIO;
                MPNOMBREUSUARIO=Principal.NOMBREEMPLEADO;
                IDTURNOCAJA=objCtrlCa.ConsecutivoCodigoDB();
                TurnoCaja tc=new TurnoCaja();
                    tc.setIdTurnoCaja(IDTURNOCAJA);
                    tc.setIdUsuario(Principal.IDUSUARIO);
                    tc.setCodCaja(codigoCaja);
                    tc.setFecha(Date.valueOf(objCtrlL.fechaNow()));
                    tc.setHoraInicial(Time.valueOf(objCtrlL.horaNow()));                
                objCtrlCa.insertTurnoCaja(tc);//inserta el turnoCaja
            }else{
                bandera=false;
                JOptionPane.showMessageDialog(null,"<html><h3 style='color:red;'>No existe ese codigo de Caja!</h3></html>"); 
            }
            
            if(bandera==false){//MENSAJE PARA CONTINUAR DIGITANDO CODIGO CAJA O NO SEGUIR Y SALIR DEL SISTEMA
                int rpta=JOptionPane.showConfirmDialog(null, "<html><h3>¿Desea digitar otra vez el Codigo de Caja?</h3></html>");
                if(rpta==1){
                    System.exit(0);
                    return;                
                }
            }            
            
        }while(bandera==false);
    }
    
    
    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
//        if(usuario==null){
               usuario=new UsuarioGui();
               contenedor.add(usuario);
               contenedor.getDesktopManager().maximizeFrame(usuario);
               usuario.setVisible(true);
//           }else{
//               contenedor.getDesktopManager().maximizeFrame(usuario);
//           }  
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnUsuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane contenedor;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
